# Generated by Django 2.1.2 on 2018-10-24 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_liftit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='identification',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='test_liftit.Brand'),
        ),
    ]
